#!/bin/bash
# Clear anamnesis experience data for testing.
# Preserves directory structure (.gitkeep) and entity/knowledge (not generated by anamnesis).

AGENTS_DIR="${LUCY_AGENTS_DIR:-.agents}"
EXP_DIR="$AGENTS_DIR/experience"

echo "[clear-experience] Clearing $EXP_DIR"

# Memory
rm -f "$EXP_DIR/memory/MEMORY.md"
rm -f "$EXP_DIR/memory/questions.md"
rm -f "$EXP_DIR/memory/predictions.md"
rm -f "$EXP_DIR/memory/releases/log.md"
rm -rf "$EXP_DIR/memory/reflections/"*.json

# Narrative
rm -f "$EXP_DIR/narrative/journal.md"
rm -f "$EXP_DIR/narrative/journal-archive-"*.md
rm -f "$EXP_DIR/narrative/identity.md"
rm -f "$EXP_DIR/narrative/arcs.md"
rm -f "$EXP_DIR/narrative/tensions/active.md"
rm -f "$EXP_DIR/narrative/relations/"*.md

# Dispositions
rm -f "$EXP_DIR/dispositions/profile.md"

echo "[clear-experience] Done. Entity and knowledge untouched."
