name: pull-request

env:
  node-version: 18.19.0 # should be in line with .nvmrc

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
        working-directory: app
      - name: Lint
        run: npm run lint
        working-directory: app

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - name: Setup node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ env.node-version }}
  #         cache: 'npm'
  #     - name: Setup nx shas
  #       uses: nrwl/nx-set-shas@v3
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Test
  #       run: npm run test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
        working-directory: app
      - name: Build
        run: npm run build
        working-directory: app
