

name: Pull Request Workflow

env:
  node-version: 20.15.0
  NODE_ENV: test
  PORT: 3000
  OPENAI_API_KEY: dummy
  TODOIST_API_KEY: dummy
  JWT_ACCESS_SECRET: dummy
  JWT_REFRESH_SECRET: dummy
  DB_HOST: localhost
  DB_PORT: 5432
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_NAME: postgres
  CORS_ORIGIN: http://localhost:3000

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  lint-shared-dto:
    name: 🛠️ Lint Shared DTO
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: shared-dto
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
          cache-dependency-path: './shared-dto/package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint

  build-shared-dto:
    name: 🚀 Build Shared DTO
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: shared-dto
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
          cache-dependency-path: './shared-dto/package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: Build code
        run: npm run build

  lint-backend:
    name: 🛠️ Lint Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
          cache-dependency-path: './app/package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
  
  lint-frontend:
    name: 🛠️ Lint Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
          cache-dependency-path: './web/package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint

  test-backend:
    name: 🧪 Test Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
          cache-dependency-path: './app/package-lock.json'
      - name: PreBuild Shared DTO
        run: npm run prebuild
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test

  build-backend:
    name: 🚀 Build Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
          cache-dependency-path: './app/package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: PreBuild Shared DTO
        run: npm run prebuild
      - name: Build code
        run: npm run build

  build-frontend:
    name: 🚀 Build Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
          cache-dependency-path: './web/package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: PreBuild Shared DTO
        run: npm run prebuild
      - name: Build code
        run: npm run build
