name: pull-request

env:
  node-version: 20.15.0
  NODE_ENV: test
  PORT: 3000
  OPENAI_API_KEY: dummy
  SLACK_BOT_TOKEN: dummy
  SLACK_APP_LEVEL_TOKEN: dummy
  TODOIST_API_KEY: dummy
  JWT_ACCESS_SECRET: dummy
  JWT_REFRESH_SECRET: dummy
  DB_HOST: localhost
  DB_PORT: 5432
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_NAME: postgres
  CORS_ORIGIN: http://localhost:3000

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:


jobs:
  lint-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
        working-directory: web
      - name: Lint
        run: npm run lint
        working-directory: web

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
        working-directory: app
      - name: Test
        run: npm run test
        working-directory: app

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
        working-directory: app
      - name: Build
        run: npm run build
        working-directory: app

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
        working-directory: web
      - name: Build
        run: npm run build
        working-directory: web
